apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bck02-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: <your-block-storage-class>
