apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bck03-pvc-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: <block-sc>
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bck03-pvc-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: <block-sc>
