apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bck06-rwx-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: <rwx-storage-class>
